name: 🚀 Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide detailed information to help us understand and implement your request.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Provide a clear and concise description of the feature you'd like to see implemented.
      placeholder: Describe the feature you want to add...
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it address?
      placeholder: This feature would solve...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution in detail.
      placeholder: The solution could work by...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches?
      placeholder: Alternative approaches could include...
    validations:
      required: false

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature is to implement?
      options:
        - Low (few hours)
        - Medium (few days)
        - High (weeks or more)
        - Unknown
    validations:
      required: true

  - type: checkboxes
    id: implementation-considerations
    attributes:
      label: Implementation Considerations
      description: Please check all that apply to this feature request.
      options:
        - label: This feature requires security review
        - label: This feature needs comprehensive testing
        - label: This feature affects user interface
        - label: This feature requires documentation updates
        - label: This feature has performance implications
        - label: This feature needs database changes
        - label: I'm willing to help implement this feature

  - type: dropdown
    id: auto-implement
    attributes:
      label: Auto-Implementation
      description: Would you like Claude to attempt automatic implementation for simple features?
      options:
        - "No, I prefer manual implementation"
        - "Yes, if complexity is Low"
        - "Yes, regardless of complexity"
      default: 1
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request.
      placeholder: Additional information...
    validations:
      required: false